theme: jekyll-theme-tactile

header_pages:
  - url: deployment.html
  - url: TopicModel_Letters1916-1923.html
  - url: casestudy1.html
  - url: casestudy2.html
  - url: publications.html
  - url: contact-us.html
