var json_IWHSOregionaldepots_8 = {
"type": "FeatureCollection",
"name": "IWHSOregionaldepots_8",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Source": "21 February 1919, Third Annual Report of the Sphagnum Department of the Irish War Hospital Supply Organisation \/ Leinster Express 1831-current, Saturday, December 11, 1915; Page: 5 \/ Leinster Express 1831-current, Saturday, March 04, 1916; Page: 4 ", "Unit no.": "none ", "Function": "moss depot & regional supply depot ", "Work party \/ supply depot address": "not stated ", "Town": "Abbeyleix ", "Full Address": "Abbeyleix Ireland ", "County (ancient)": "Queen’s County ", "County (modern)": "Laois ", "Opened": "Dec. 1915 ", "Closed": "[1919] ", "Established \/ run by (last name)": "Marchioness of Waterford ", "First and middle names": "", "Gender": "", "Marital status": "", "Collaborators": "" }, "geometry": { "type": "Point", "coordinates": [ -7.3478923, 52.9152801 ] } },
{ "type": "Feature", "properties": { "Source": "Derry Journal 1844-1924, Monday, December 13, 1915; Page: 3 \/ Derry Journal 1844-1924, Wednesday, February 23, 1916; Page: 2 \/ Derry Journal 1844-1924, Friday, November 24, 1916; Page: 7 ", "Unit no.": "none ", "Function": "regional moss depot for the NORTH WEST OF IRELAND ", "Work party \/ supply depot address": "STRAND HOUSE ", "Town": "Derry \/ Londonderry ", "Full Address": "Londonderry Ireland ", "County (ancient)": "", "County (modern)": "", "Opened": "[01\/01\/1916] ", "Closed": "[1919] ", "Established \/ run by (last name)": "Lily E. Anderson (Mayoress) \/ the Duchess of Abercorn ", "First and middle names": "", "Gender": "", "Marital status": "", "Collaborators": "" }, "geometry": { "type": "Point", "coordinates": [ -7.3085748, 54.9966124 ] } },
{ "type": "Feature", "properties": { "Source": "Connacht Tribune 1909-current, Saturday, September 09, 1916; Page: 8 ", "Unit no.": "none ", "Function": "regional supply depot ", "Work party \/ supply depot address": "house to be taken", "Town": "Galway ", "Full Address": "Galway Ireland ", "County (ancient)": "Galway ", "County (modern)": "", "Opened": "Sept. 1916 ", "Closed": "[1919] ", "Established \/ run by (last name)": "Lady Ashtown ", "First and middle names": "", "Gender": "f ", "Marital status": "married ", "Collaborators": "" }, "geometry": { "type": "Point", "coordinates": [ -9.0567905, 53.270668 ] } }
]
}
