var json_mossdepotsinitiallygeneralsupply_1 = {
"type": "FeatureCollection",
"name": "mossdepotsinitiallygeneralsupply_1",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Source": "21 February 1919, Third Annual Report of the Sphagnum Department of the Irish War Hospital Supply Organisation \/ Irish Examiner 1841-current, Thursday, September 09, 1915; Page: 7 ", "Unit no.": "none ", "Function": "moss depot (initially installed as general supply depot) ", "Work party \/ supply depot address": "not stated ", "Town": "Cahir ", "Full Address": "Cahir Ireland ", "County (ancient)": "", "County (modern)": "", "Opened": "1915-1919 ", "Closed": "[1919] ", "Established \/ run by (last name)": "Blakeney ", "First and middle names": "not stated ", "Gender": "f ", "Marital status": "married ", "Collaborators": "" }, "geometry": { "type": "Point", "coordinates": [ -7.925247, 52.3745296 ] } },
{ "type": "Feature", "properties": { "Source": "21 February 1919, Third Annual Report of the Sphagnum Department of the Irish War Hospital Supply Organisation \/ Waterford News and Star 1848-current, Friday, July 09, 1915; Page: 8 ", "Unit no.": "none ", "Function": "moss depot (initially planned as general supply depot) ", "Work party \/ supply depot address": "not stated ", "Town": "Portlaw ", "Full Address": "Portlaw Ireland ", "County (ancient)": "", "County (modern)": "", "Opened": "1915- ", "Closed": "[1919] ", "Established \/ run by (last name)": "Lady Waterford ", "First and middle names": "", "Gender": "f ", "Marital status": "married ", "Collaborators": "" }, "geometry": { "type": "Point", "coordinates": [ -7.3144407, 52.2881989 ] } },
{ "type": "Feature", "properties": { "Source": "21 February 1919, Third Annual Report of the Sphagnum Department of the Irish War Hospital Supply Organisation \/ Waterford News and Star 1848-current, Friday, July 09, 1915; Page: 8 \/ Waterford News and Star 1848-current, Friday, July 27, 1917; Page: 12 ", "Unit no.": "moss depot ", "Function": "moss depot (initially planned as general supply depot) ", "Work party \/ supply depot address": "not stated ", "Town": "Tramore ", "Full Address": "Tramore Ireland ", "County (ancient)": "", "County (modern)": "", "Opened": "1915- ", "Closed": "[1919] ", "Established \/ run by (last name)": "Lady Waterford ", "First and middle names": "", "Gender": "f ", "Marital status": "married ", "Collaborators": "" }, "geometry": { "type": "Point", "coordinates": [ -7.1492952, 52.1614354 ] } }
]
}
