var json_subdepotsaffiliated_5 = {
"type": "FeatureCollection",
"name": "subdepotsaffiliated_5",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Source": "Anglo-Celt 1846-current, Saturday, December 23, 1916; Page: 4 ", "Unit no.": "none ", "Function": "general sub-depot (affiliated with Monaghan) ", "Work party \/ supply depot address": "not stated ", "Town": "Castleshane ", "Full Address": "Castleshane Ireland ", "County (ancient)": "", "County (modern)": "Monaghan ", "Opened": "[1916] ", "Closed": "[1919] ", "Established \/ run by (last name)": "Mrs. Lucas-Scudamore? ", "First and middle names": "", "Gender": "f ", "Marital status": "married ", "Collaborators": "" }, "geometry": { "type": "Point", "coordinates": [ -6.88389, 54.23806 ] } },
{ "type": "Feature", "properties": { "Source": "Derry Journal 1844-1924, Monday, April 08, 1918; Page: 4 ", "Unit no.": "none ", "Function": "general supply depot (affiliated with Coleraine?) ", "Work party \/ supply depot address": "wanted to use a school room in a Methodist church but had to look elsewhere when the pastor objected? ", "Town": "Portstewart ", "Full Address": "Portstewart Ireland ", "County (ancient)": "Derry ", "County (modern)": "Causeway Coast & Glens ", "Opened": "April 1918 ", "Closed": "[1919] ", "Established \/ run by (last name)": "", "First and middle names": "", "Gender": "", "Marital status": "", "Collaborators": "" }, "geometry": { "type": "Point", "coordinates": [ -6.71402, 55.18132 ] } },
{ "type": "Feature", "properties": { "Source": "Leinster Express 1831-current, Saturday, August 12, 1916; Page: 3 ", "Unit no.": "none ", "Function": "sub-depot affiliated with Abbeyleix ", "Work party \/ supply depot address": "Stradbally Hall ", "Town": "Stradbally ", "Full Address": "Stradbally Ireland ", "County (ancient)": "Queen's County ", "County (modern)": "Laois ", "Opened": "1916 ", "Closed": "[1919] ", "Established \/ run by (last name)": "", "First and middle names": "", "Gender": "", "Marital status": "", "Collaborators": "" }, "geometry": { "type": "Point", "coordinates": [ -7.16667, 53.0 ] } }
]
}
